# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emily Warman
bio:
  I write about software development and my life (which is ~70% software development)
  <br><br>
  üìç  San Francisco
  <br>
  üíº  Engineering Resident @ Google
description: A software development and software development lifestyle blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.emilywarman.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ewarman
author: Emily Warman
# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

plugins: ['kramdown', 'jekyll-analytics', 'jekyll-feed', 'jekyll-seo-tag']

include: ['_pages']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'heroku_apps_list']

jekyll_analytics:
  GoogleAnalytics:
    id: UA-61768938-1
    anonymizeIp: false

permalink: /:title.html
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
